import { expect, test } from "@playwright/test";

test("sorts each color, re-jumbles during a pickup and after completion, and returns to Build", async ({ page }) => {
  test.setTimeout(300_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  const hero = page.locator("#simulator");
  await expect(hero.getByRole("tab", { name: "Sort", exact: true })).toBeEnabled({ timeout: 30_000 });
  await hero.getByRole("tab", { name: "Sort", exact: true }).click();
  await page.getByLabel("Simulation speed").fill("4");
  await expect(hero).toHaveAttribute("data-workspace", "sort");
  await expect(hero).toHaveAttribute("data-supply", "8");
  await expect(hero).toHaveAttribute("data-build", "running");
  await expect(hero).toHaveAttribute("data-held", /object/, { timeout: 30_000 });
  await hero.getByRole("button", { name: "Pause", exact: true }).click();
  await expect(hero).toHaveAttribute("data-paused", "true");
  await page.screenshot({ path: `/tmp/robot-sort-${test.info().project.name}.png` });
  await hero.getByRole("button", { name: "Re-jumble & sort" }).click();
  await expect(hero).toHaveAttribute("data-sort-round", "2");
  await expect(hero).toHaveAttribute("data-paused", "false");
  await expect(hero).toHaveAttribute("data-placed", "0");
  await expect(hero).toHaveAttribute("data-build", "complete", { timeout: 150_000 });
  await expect(hero).toHaveAttribute("data-placed", "8");
  for (const color of ["red", "blue", "yellow", "green"]) await expect(hero.locator(`.sort-color[data-color="${color}"]`)).toHaveAttribute("data-sorted", "2");
  await hero.getByRole("button", { name: "Re-jumble & sort" }).click();
  await expect(hero).toHaveAttribute("data-sort-round", "3");
  await expect(hero).toHaveAttribute("data-build", "running");
  await hero.getByRole("tab", { name: "Joints", exact: true }).click();
  await hero.getByRole("button", { name: "Home", exact: true }).click();
  await expect(hero).toHaveAttribute("data-build", "stopped");
  await hero.getByRole("tab", { name: "Sort", exact: true }).click();
  await expect(hero.getByRole("button", { name: "Start sorting" })).toBeVisible();
  await hero.getByRole("tab", { name: "Build", exact: true }).click();
  await expect(hero).toHaveAttribute("data-workspace", "build");
  await expect(hero).toHaveAttribute("data-preset", "pavilion");
  await expect(hero).toHaveAttribute("data-build", "idle");
  expect(errors).toEqual([]);
});
